import {ORDER_STATUS} from "./OrderStatus";

export enum ORDER_ACTION {
    MAKE = '0',
    REJECT = '1',
    ASSEMBLER_REFUSE = '2',
    COURIER_REFUSE = '3',
    TO_ASSEMBLY = '4',
    TO_ASSEMBLED = '5',
    TO_DELIVERY = '6',
    TO_DELIVERED = '7'
}

export const ORDER_ACTION_MAPPER : {[char: string]: string} = {
    "MAKE": ORDER_STATUS.PLACED,
    "ASSEMBLER_REFUSE" : ORDER_STATUS.PLACED,
    "TO_ASSEMBLY": ORDER_STATUS.ASSEMBLING,
    "TO_ASSEMBLED": ORDER_STATUS.ASSEMBLED,
    "COURIER_REFUSE" : ORDER_STATUS.ASSEMBLED,
    "TO_DELIVERY": ORDER_STATUS.DELIVERING,
    "TO_DELIVERED": ORDER_STATUS.DELIVERED,
}
