import {ORDER_ACTION_REQUEST} from "./OrderAction";

export enum ORDER_STATUS {
    MAKING = 'MAKING',
    PLACED = 'PLACED',
    ASSEMBLING = 'ASSEMBLING',
    ASSEMBLED = 'ASSEMBLED',
    DELIVERING = 'DELIVERING',
    DELIVERED = 'DELIVERED',
    REJECTED = 'REJECTED'
}

export const ORDER_STATUS_MAPPER : {[char: string]: string} = {
    [ORDER_STATUS.MAKING]: 'Делается',
    [ORDER_STATUS.PLACED]: 'Скоро начнем собирать!',
    [ORDER_STATUS.ASSEMBLING]: 'Собираем заказ!',
    [ORDER_STATUS.ASSEMBLED]: 'Ждем курьера!',
    [ORDER_STATUS.DELIVERING]: 'Курьер уже в пути!',
    [ORDER_STATUS.DELIVERED]: `Доставлен`,
    [ORDER_STATUS.REJECTED]: 'Отменен',
}

export enum ORDER_STATUS_REQUEST {
    MAKING,
    PLACED,
    ASSEMBLING,
    ASSEMBLED,
    DELIVERING,
    DELIVERED,
    REJECTED

}
export const ORDER_STATUS_REQUEST_MAPPER : {[char: string]: number} = {
    [ORDER_STATUS.MAKING]: ORDER_STATUS_REQUEST.MAKING,
    [ORDER_STATUS.PLACED]: ORDER_STATUS_REQUEST.PLACED,
    [ORDER_STATUS.ASSEMBLING]: ORDER_STATUS_REQUEST.ASSEMBLING,
    [ORDER_STATUS.ASSEMBLED]: ORDER_STATUS_REQUEST.ASSEMBLED,
    [ORDER_STATUS.DELIVERING]: ORDER_STATUS_REQUEST.DELIVERING,
    [ORDER_STATUS.DELIVERED]: ORDER_STATUS_REQUEST.DELIVERED,
}
